typography_spectrum: 0.723790941564274
color:
  brandStrength: 0.4149426195806464
  lightness: 0.5487673397836192
  saturation: 0.6720655133106774
  rhythmicContrast: 0.2601029585820097
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
layout_spectrum: 0.8145747593884347
analytics:
  google: UA-87385729-2
author:
  name: Mont Sinai Innovatiion Consulting
  email: info@montsinai.eu
  url: 'http://www.montsinai.eu'
logo: null
name: Innovation Consulting
favicon: null
title: Innovation Consulting
content: []
coverPrefs:
  filter: false
description: Help you with your innovation challenges
purpose:
  - type: contact
    url: 'mailto:info@montsinai.eu'
    label: Contact me
github: true
url: 'http://montsinai.eu/'
