layout_spectrum: 0.4158777752784219
typography_spectrum: 0.5029483540375523
color:
  brandStrength: 0.01368889680796183
  lightness: 0.41747308328904503
  saturation: 0.8864556761944463
  rhythmicContrast: 0.9280474614866521
  brandColors:
    - '#F9E4AD'
    - '#E6B098'
    - '#CC4452'
    - '#723147'
    - '#31152B'
coverPrefs:
  filter: false
analytics:
  google: UA-87385729-2
author:
  name: Mont Sinai Innovatiion Consulting
  email: info@montsinai.eu
  url: 'http://www.montsinai.eu'
logo: null
name: Innovation Consulting
favicon: null
title: Innovation Consulting
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/83db1dd1-4e3e-429b-8b6d-d77f1e81b800.gif">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/83db1dd1-4e3e-429b-8b6d-d77f1e81b800.gif
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Help you with your innovation challenges
purpose:
  - type: contact
    url: 'mailto:info@montsinai.eu'
    label: Contact me
github: true
url: 'http://montsinai.eu/'
