layout_spectrum: 0.1277889551256442
typography_spectrum: 0.9193784938557166
color:
  brandStrength: 0.8683226567885773
  lightness: 0.6601092360073719
  saturation: 0.15841977028176188
  rhythmicContrast: 0.7133575850677224
  brandColors:
    - '#F9E4AD'
    - '#E6B098'
    - '#CC4452'
    - '#723147'
    - '#31152B'
coverPrefs:
  filter: false
analytics:
  google: UA-87385729-2
author:
  name: Mont Sinai Innovatiion Consulting
  email: info@montsinai.eu
  url: 'http://www.montsinai.eu'
logo: null
name: Innovation Consulting
favicon: null
title: Innovation Consulting
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/6f06f4df-045d-4cf4-bc3d-62142afd0db4.gif">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/6f06f4df-045d-4cf4-bc3d-62142afd0db4.gif
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Help you with your innovation challenges
purpose:
  - type: contact
    url: 'mailto:info@montsinai.eu'
    label: Contact me
github: true
url: 'http://montsinai.eu/'
